INSERT INTO usuarios (data)
VALUES 
  ('{"nombre": "Ana", "activo": true, "edad": 30}'),
  ('{"nombre": "Juan", "activo": false, "edad": 25}');

INSERT INTO productos(precio,atributos,atributosH) values
(100.00,'{"NOMBRE":"LIBRETA","COLOR":"ROJO","TAMANO":"PEQUENO","CATEGORIA":"PAPELERIA"}',
'MARCA=>SCRIBE,COLOR=>ROJO,PESO=>60G'),

(15.00,'{"NOMBRE":"LAPIZ","TAMANO":"PEQUENO","CATEGORIA":"PAPELERIA"}',
'MARCA=>SCRIBE,PESO=>10G'),

(480.50,'{"NOMBRE":"LIBRO","COLOR":"AMARILLO","CATEGORIA":"PAPELERIA"}',
'COLOR=>AMARILLO,PESO=>60G'),

(6500.00,'{"NOMBRE":"CELULAR","COLOR":"NEGRO","CATEGORIA":"TECNOLOGIA"}',
'MARCA=>SAMSUNG,COLOR=>NEGRO,PESO=>150G'),

(4500.00,'{"NOMBRE":"RELOJ","COLOR":"ROJO","CATEGORIA":"TECNOLOGIA"}',
'MARCA=>SAMSUNG,COLOR=>ROJO,PESO=>100G');
